/* ==========================================================================
   WASHINGTON POLICE DEPARTMENT: CIVIC DATASET & DIRECTORY
   Districts, Street Mapping, 24/7 Patrol Operations & Resident Services
   Strict Direct-Linking to Official City Portals + 5 In-App Smart Drawers
   ========================================================================== */

const WPD_DATA = {
  identity: {
    name: "Washington Police Department",
    motto: "Serve with Honor, Protect with Purpose, Lead with Integrity",
    established: 1825,
    chief: "Jeff Stevens",
    chiefTitle: "Chief of Police",
    address: "115 W. Jefferson St., Washington, IL 61571",
    emergency: "911",
    nonEmergency: "(309) 444-2313",
    fax: "(309) 444-7511",
    social: {
      facebook: "https://www.facebook.com/WashingtonPoliceDepartment",
      instagram: "https://www.instagram.com/washington_il_police_dept/"
    },
    lobbyHours: "Monday – Friday: 8:00 AM – 4:30 PM (Records & Administrative Window)",
    patrolHours: "Continuous 24 Hours a Day, 7 Days a Week, 365 Days a Year"
  },

  watches: [
    {
      id: "shift-day",
      name: "Day Shift",
      hours: "07:00 – 15:00",
      startHour: 7,
      endHour: 15,
      supervisor: "On-Duty Patrol Sergeant",
      focus: "School zones, business district patrols, traffic safety, municipal court details"
    },
    {
      id: "shift-afternoon",
      name: "Afternoon Shift",
      hours: "15:00 – 23:00",
      startHour: 15,
      endHour: 23,
      supervisor: "On-Duty Patrol Sergeant",
      focus: "School dismissal, rush hour traffic flow, commercial retail corridors, park checks"
    },
    {
      id: "shift-night",
      name: "Night Shift",
      hours: "23:00 – 07:00",
      startHour: 23,
      endHour: 7,
      supervisor: "On-Duty Patrol Sergeant",
      focus: "Commercial business security checks, residential neighborhood patrols, traffic safety, and vacation house checks"
    }
  ],

  districts: {
    1: {
      id: 1,
      name: "District 1 (Historic Core & East Sector)",
      color: "#2563EB",
      coverage: "Historic Downtown Square, Devonshire, WCHS & Washington Middle School (North Main)",
      acres: "433.6 Acres",
      boundaries: "Territory east of North Wilmor Road to eastern municipal limits, bounded by Devonshire Road and North Main Street corridors to the north, encompassing Historic Downtown Square, WPD Police Headquarters, City Hall, Washington Middle School (District 52 on North Main), Lincoln Grade School, and Washington Community High School.",
      landmarks: [
        "Historic Downtown Washington Square & Fountain",
        "WPD Police Headquarters (115 W. Jefferson St)",
        "Washington City Hall (301 Walnut St)",
        "Washington Middle School (District 52 / 1100 N. Main St)",
        "Washington Community High School (District 308 / 115 Bondurant St)",
        "Lincoln Grade School (375 W. Peoria St / Rec Trail)",
        "Devonshire Estates & Devonshire Road",
        "Fire Station 2 (105 S. Spruce St)"
      ],
      sectorCar: "Sector Car 101",
      supervisor: "East & Core Sector Sergeant",
      priority: "Downtown commercial district, school zone transit safety, Devonshire neighborhood coverage, East Route 24 coordination"
    },
    2: {
      id: 2,
      name: "District 2 (West Sector)",
      color: "#059669",
      coverage: "West Washington, Freedom Parkway Hub, ALDI Commercial Corridor & Western Subdivisions",
      acres: "1,681.4 Acres",
      boundaries: "Territory south of Washington Road (Business 24) from Wilmor Road west to Cummings Lane, and extending across the entire western municipal boundaries west of Cummings Lane, including Freedom Parkway retail corridor, ALDI, Centennial Drive, and Meadow Valley Park.",
      landmarks: [
        "Freedom Parkway Retail Center & Walmart Supercenter",
        "ALDI (1110 Peoria St / Washington Plaza)",
        "Meadow Valley Park (525 Ernest St)",
        "Peoria Street Western Commercial Corridor",
        "South Cummings Lane Corridor",
        "Washington Estates & Western Subdivisions"
      ],
      sectorCar: "Sector Car 102",
      supervisor: "West Sector Sergeant",
      priority: "Retail loss deterrence, commercial speed enforcement, ALDI corridor safety, western residential neighborhood patrols"
    },
    3: {
      id: 3,
      name: "District 3 (North Sector / Bypass)",
      color: "#7C3AED",
      coverage: "Five Points Washington, Central School Campus, North Wilmor & Route 24 Bypass",
      acres: "1,476.7 Acres",
      boundaries: "Territory north of Washington Road (Business 24) between Cummings Lane and Wilmor Road, extending north to the US Route 24 Bypass, West Cruger Road, and northern municipal limits, including Five Points Washington, Central Primary School, Central Intermediate School, and Fire Station 1.",
      landmarks: [
        "Five Points Washington Community Center (360 N. Wilmor Rd)",
        "Central Primary School (District 51 / 1400 Newcastle Rd)",
        "Central Intermediate School (District 51 / 1301 Eagle Ave)",
        "Washington Fire Station 1 (200 N. Wilmor Rd)",
        "Cherry Tree Shopping Center & Kroger (North side Peoria St)",
        "US Route 24 Bypass Commercial & Cruger Corridors",
        "Rolling Meadows & Oak Creek Subdivisions"
      ],
      sectorCar: "Sector Car 103",
      supervisor: "North Sector Sergeant",
      priority: "School zone arrival safety, Five Points community facility security, Bypass corridor traffic management, northern neighborhood patrols"
    }
  },

  /* Washington Street Directory for Instant Address-to-Patrol Beat GIS Resolver */
  /* Complete Municipal Jurisdiction: 433 Verified Streets Across Districts 1, 2, and 3 */
  streets: [
    { name: "9-1-1 Dr", district: 1, area: "East Sector Residential" },
    { name: "911 Dr", district: 1, area: "East Sector Residential" },
    { name: "Agnes St", district: 3, area: "North Sector Residential" },
    { name: "Amanda Ln", district: 2, area: "West Sector Residential" },
    { name: "Anne St", district: 3, area: "North Sector Residential" },
    { name: "Anthony Ct", district: 3, area: "North Sector Residential" },
    { name: "Arbor Way", district: 3, area: "North Sector Residential" },
    { name: "Ash", district: 3, area: "North Sector Residential" },
    { name: "Ash St", district: 3, area: "North Sector Residential" },
    { name: "Aspen Dr", district: 3, area: "North Sector Residential" },
    { name: "Austin Ave", district: 3, area: "North Sector Residential" },
    { name: "Autumn Ridge Dr", district: 3, area: "Rolling Meadows & Northern Subdivisions" },
    { name: "Avon Ct", district: 1, area: "Devonshire Estates / East Subdivisions" },
    { name: "Bayberry Dr", district: 2, area: "West Sector Residential" },
    { name: "Belaire Ct", district: 2, area: "Meadow Valley / Western Subdivisions" },
    { name: "Belaire Dr", district: 2, area: "Meadow Valley / Western Subdivisions" },
    { name: "Belford Ct", district: 1, area: "Devonshire Estates / East Subdivisions" },
    { name: "Birchwood Dr", district: 1, area: "Historic Downtown Core / WCHS Campus" },
    { name: "Birkett Ct", district: 1, area: "East Sector Residential" },
    { name: "Birkett Ln", district: 1, area: "East Sector Corridor" },
    { name: "Bishops Ct", district: 1, area: "East Sector Residential" },
    { name: "Bobolink Dr", district: 3, area: "Rolling Meadows & Northern Subdivisions" },
    { name: "Bondurant St", district: 1, area: "WCHS Campus Corridor" },
    { name: "Breeze Way", district: 1, area: "East Sector Residential" },
    { name: "Brentwood Ct", district: 2, area: "Historic Downtown Core / WCHS Campus" },
    { name: "Brentwood Dr", district: 2, area: "Historic Downtown Core / WCHS Campus" },
    { name: "Briar Ct", district: 2, area: "West Sector Residential" },
    { name: "Briar Ln", district: 2, area: "West Sector Residential" },
    { name: "Briarcliff Dr", district: 2, area: "Meadow Valley / Western Subdivisions" },
    { name: "Brief St", district: 1, area: "East Sector Residential" },
    { name: "Bristol Ct", district: 1, area: "Devonshire East Subdivisions" },
    { name: "Brook Crest Dr", district: 1, area: "East Sector Residential" },
    { name: "Brookcrest Dr", district: 1, area: "East Sector Residential" },
    { name: "Brookshire Dr", district: 2, area: "West Sector Residential" },
    { name: "Brown Ct", district: 3, area: "North Sector Residential" },
    { name: "Brown Dr", district: 3, area: "North Sector Residential" },
    { name: "Browning Ct", district: 3, area: "North Sector Residential" },
    { name: "Burton", district: 1, area: "Historic Downtown Core / WCHS Campus" },
    { name: "Burton St", district: 1, area: "Historic Downtown Core / WCHS Campus" },
    { name: "Calvin Dr", district: 3, area: "North Sector Residential" },
    { name: "Cambridge Dr", district: 3, area: "North Residential Subdivisions" },
    { name: "Candlewood", district: 1, area: "Historic Downtown Core / WCHS Campus" },
    { name: "Candlewood Dr", district: 1, area: "Historic Downtown Core / WCHS Campus" },
    { name: "Canterbury Dr", district: 3, area: "North Residential Subdivisions" },
    { name: "Catherine St", district: 1, area: "East Central" },
    { name: "Cayman Ln", district: 2, area: "West Sector Residential" },
    { name: "Cedar St", district: 1, area: "East Core Residential" },
    { name: "Centennial Dr", district: 2, area: "West Residential / Connector Artery" },
    { name: "Central Ave", district: 1, area: "East Sector Residential" },
    { name: "Central St", district: 1, area: "East Sector Residential" },
    { name: "Charlotte St", district: 2, area: "West Sector Residential" },
    { name: "Charter Oak Dr", district: 3, area: "North Subdivisions" },
    { name: "Chelsea Pl", district: 1, area: "Devonshire Estates / East Subdivisions" },
    { name: "Cherry Tree Shopping Ctr", district: 3, area: "Kroger Commercial Center" },
    { name: "Chester Ct", district: 1, area: "Devonshire East Subdivisions" },
    { name: "Chestnut Ln", district: 3, area: "North Sector Residential" },
    { name: "Chrisendale Ln", district: 1, area: "East Sector Residential" },
    { name: "Cobblestone", district: 2, area: "West Sector Residential" },
    { name: "Colonial Ct", district: 2, area: "West Sector Residential" },
    { name: "Colt Dr", district: 3, area: "North Sector Residential" },
    { name: "Comfort Way", district: 1, area: "East Sector Residential" },
    { name: "Constitution Ave", district: 3, area: "North Bypass Corridor" },
    { name: "Country Fair Dr", district: 2, area: "Meadow Valley / Western Subdivisions" },
    { name: "Countryview Ct", district: 2, area: "West Sector Residential" },
    { name: "County Highway 3 (Cruger Rd)", district: 1, area: "Historic Downtown Core / WCHS Campus" },
    { name: "Court Dr", district: 1, area: "Historic Downtown Core / WCHS Campus" },
    { name: "Courtney Dr", district: 3, area: "Historic Downtown Core / WCHS Campus" },
    { name: "Coventry Dr", district: 1, area: "East Sector Residential" },
    { name: "Cranford Dr", district: 3, area: "North Sector Residential" },
    { name: "Crestview Dr", district: 1, area: "East Sector Residential" },
    { name: "Cruger Rd", district: 3, area: "North Cruger Bypass Corridor" },
    { name: "Cummings Ln", district: 2, area: "West Sector Patrol Artery" },
    { name: "Dallas Rd", district: 3, area: "North Residential Corridor" },
    { name: "Danforth", district: 1, area: "Historic Downtown Core / WCHS Campus" },
    { name: "Danforth St", district: 1, area: "Historic Downtown Core / WCHS Campus" },
    { name: "Debates St", district: 3, area: "North Sector Residential" },
    { name: "Deer Ln", district: 3, area: "North Sector Residential" },
    { name: "Devon Ln", district: 1, area: "East Sector Residential" },
    { name: "Devonshire Rd", district: 1, area: "Devonshire Estates" },
    { name: "Dieble Rd", district: 1, area: "East Sector Residential" },
    { name: "Dixon St", district: 2, area: "West Sector Residential" },
    { name: "Dogwood", district: 2, area: "Historic Downtown Core / WCHS Campus" },
    { name: "Dogwood Dr", district: 2, area: "Historic Downtown Core / WCHS Campus" },
    { name: "Dorchester Ct", district: 1, area: "Devonshire Estates / East Subdivisions" },
    { name: "Drake Ln", district: 3, area: "North Sector Residential" },
    { name: "E Adams St", district: 1, area: "Historic Downtown Core / WCHS Campus" },
    { name: "E Cruger Rd", district: 1, area: "Cruger Bypass / North Corridor" },
    { name: "E Guth Rd", district: 1, area: "East Sector Residential" },
    { name: "E Holland St", district: 1, area: "Historic Downtown Core / WCHS Campus" },
    { name: "E Jefferson St", district: 1, area: "Historic Downtown Core / WCHS Campus" },
    { name: "E Yorktown Ct", district: 2, area: "West Sector Residential" },
    { name: "Eagle Ave", district: 3, area: "Central Intermediate School Corridor" },
    { name: "East Adams St", district: 1, area: "Historic Downtown Core / WCHS Campus" },
    { name: "East Cruger Rd", district: 1, area: "Cruger Bypass / North Corridor" },
    { name: "East Guth Rd", district: 1, area: "East Sector Residential" },
    { name: "East Holland St", district: 1, area: "Historic Downtown Core / WCHS Campus" },
    { name: "East Jefferson St", district: 1, area: "East Residential Corridor" },
    { name: "East Yorktown Ct", district: 2, area: "West Sector Residential" },
    { name: "Easy St", district: 1, area: "East Sector Residential" },
    { name: "Edgewood Ct", district: 2, area: "Historic Downtown Core / WCHS Campus" },
    { name: "Eilers Ct", district: 1, area: "East Sector Residential" },
    { name: "Eldridge St", district: 1, area: "East Sector Residential" },
    { name: "Eleanor St", district: 1, area: "East Sector Residential" },
    { name: "Elgin Ave", district: 3, area: "North Sector Residential" },
    { name: "Elgin Ct", district: 3, area: "North Sector Residential" },
    { name: "Elk Ct", district: 3, area: "North Sector Residential" },
    { name: "Elm St", district: 1, area: "East Downtown Residential" },
    { name: "English Oak", district: 2, area: "West Sector Residential" },
    { name: "Ernest St", district: 2, area: "Meadow Valley Park Access" },
    { name: "Esken", district: 2, area: "West Sector Residential" },
    { name: "Eureka Rd", district: 1, area: "East Sector Residential" },
    { name: "Evergreen Dr", district: 2, area: "Meadow Valley / Western Subdivisions" },
    { name: "Fall St", district: 1, area: "East Sector Residential" },
    { name: "Fayette Ave", district: 3, area: "North Sector Residential" },
    { name: "Fayette Ct", district: 3, area: "North Sector Residential" },
    { name: "Fieldstone", district: 2, area: "West Sector Residential" },
    { name: "Firethorn Dr", district: 2, area: "West Sector Residential" },
    { name: "Flossmoor Ave", district: 3, area: "North Sector Residential" },
    { name: "Ford", district: 1, area: "East Sector Residential" },
    { name: "Ford Ln", district: 1, area: "East Sector Residential" },
    { name: "Foster Rd", district: 1, area: "East Sector Residential" },
    { name: "Fountaindale", district: 1, area: "East Sector Residential" },
    { name: "Fox Trl", district: 2, area: "West Sector Residential" },
    { name: "Franklin St", district: 1, area: "Historic Downtown Core / WCHS Campus" },
    { name: "Freedom Ln", district: 3, area: "North Growth Area" },
    { name: "Freedom Pkwy", district: 2, area: "Freedom Pkwy Commercial / Walmart Hub" },
    { name: "Garfield", district: 1, area: "East Sector Residential" },
    { name: "Garfield Ln", district: 1, area: "East Sector Residential" },
    { name: "Georgetown Dr", district: 1, area: "Devonshire East Subdivisions" },
    { name: "Georgetown Rd", district: 2, area: "West Sector Residential" },
    { name: "Gillman Ave", district: 3, area: "North Sector Residential" },
    { name: "Glenn St", district: 2, area: "West Sector Residential" },
    { name: "Glouster", district: 1, area: "East Sector Residential" },
    { name: "Grandyle Dr", district: 3, area: "North Sector Residential" },
    { name: "Grant St", district: 2, area: "West Sector Residential" },
    { name: "Greenbrier Ln", district: 2, area: "West Sector Residential" },
    { name: "Greendale Curve", district: 2, area: "West Sector Residential" },
    { name: "Greenfield Dr", district: 2, area: "West Sector Residential" },
    { name: "Greystone", district: 2, area: "West Sector Residential" },
    { name: "Hamilton St", district: 1, area: "East Sector Residential" },
    { name: "Hampton Rd", district: 1, area: "East Sector Residential" },
    { name: "Harding", district: 1, area: "East Sector Residential" },
    { name: "Harvey St", district: 1, area: "St. Patrick School / East" },
    { name: "Hawk St", district: 3, area: "North Sector Residential" },
    { name: "Hawthorne Pl", district: 2, area: "West Sector Residential" },
    { name: "Heather Ct", district: 2, area: "West Sector Residential" },
    { name: "Herman Essig Dr", district: 3, area: "North Sector Residential" },
    { name: "Hickory St", district: 2, area: "West Sector Residential" },
    { name: "Hidden Acres", district: 1, area: "East Sector Residential" },
    { name: "Highland", district: 1, area: "Historic Downtown Core / WCHS Campus" },
    { name: "Highland Pl", district: 1, area: "Historic Downtown Core / WCHS Campus" },
    { name: "Highwoods Rd", district: 3, area: "Historic Downtown Core / WCHS Campus" },
    { name: "Hillcrest Ct", district: 2, area: "Meadow Valley / Western Subdivisions" },
    { name: "Hillcrest Dr", district: 2, area: "West Residential Subdivisions" },
    { name: "Hilldale Ave", district: 2, area: "West Residential Corridor" },
    { name: "Hillside Rd", district: 2, area: "West Sector Residential" },
    { name: "Holborn", district: 1, area: "East Sector Residential" },
    { name: "Holland St", district: 1, area: "East Residential" },
    { name: "Hope St", district: 2, area: "West Sector Residential" },
    { name: "Hunters Way", district: 2, area: "West Sector Residential" },
    { name: "Huntington Trl", district: 2, area: "West Sector Residential" },
    { name: "Independence Ct", district: 3, area: "North Sector Residential" },
    { name: "Inglewood Dr", district: 3, area: "Historic Downtown Core / WCHS Campus" },
    { name: "Ivy Ct", district: 2, area: "West Sector Residential" },
    { name: "Jackson St", district: 1, area: "Historic Downtown Core / WCHS Campus" },
    { name: "Jadens Way", district: 3, area: "North Sector Residential" },
    { name: "Jefferson St", district: 1, area: "Historic Downtown Core / WCHS Campus" },
    { name: "Jennifer Ln", district: 1, area: "East Sector Residential" },
    { name: "Jesse St", district: 2, area: "West Sector Residential" },
    { name: "Jonathan St", district: 3, area: "North Sector Residential" },
    { name: "Kara Ct", district: 2, area: "West Sector Residential" },
    { name: "Kelsey St", district: 3, area: "North Sector Residential" },
    { name: "Kennedy", district: 2, area: "West Sector Residential" },
    { name: "Kennedy Ct", district: 2, area: "West Sector Residential" },
    { name: "Kensington Dr", district: 1, area: "Devonshire Estates / East Subdivisions" },
    { name: "Kern Rd", district: 2, area: "West Sector Residential" },
    { name: "Kingsbury Rd", district: 1, area: "Devonshire East" },
    { name: "Knollaire Dr", district: 2, area: "West Sector Residential" },
    { name: "Knollcrest Dr", district: 1, area: "East Sector Residential" },
    { name: "Labrador Way", district: 3, area: "North Sector Residential" },
    { name: "Lakeshore Dr", district: 2, area: "West Sector Residential" },
    { name: "Landau Ln", district: 1, area: "East Sector Residential" },
    { name: "Laurel Ct", district: 2, area: "West Sector Residential" },
    { name: "Lawndale Ave", district: 2, area: "West Sector Residential" },
    { name: "Lawndale Ln", district: 1, area: "East Sector Residential" },
    { name: "Lawson St", district: 2, area: "West Sector Residential" },
    { name: "Legion Rd", district: 2, area: "West Sector Residential" },
    { name: "Legion St", district: 2, area: "West Sector Residential" },
    { name: "Lexington Dr", district: 2, area: "West Sector Residential" },
    { name: "Lincoln St", district: 1, area: "Lincoln Grade School / East" },
    { name: "Linden St", district: 2, area: "West Sector Residential" },
    { name: "Linnhill Ln", district: 2, area: "West Sector Residential" },
    { name: "Linsley St", district: 2, area: "West Sector Residential" },
    { name: "Locust St", district: 2, area: "West Sector Residential" },
    { name: "Logan St", district: 1, area: "East Sector Residential" },
    { name: "Lori Ln", district: 3, area: "North Sector Residential" },
    { name: "Lynn St", district: 1, area: "East Sector Residential" },
    { name: "Lynnhaven Dr", district: 2, area: "West Sector Residential" },
    { name: "Mackenzie St", district: 3, area: "North Sector Residential" },
    { name: "Madison", district: 1, area: "East Sector Residential" },
    { name: "Madison St", district: 1, area: "East Sector Residential" },
    { name: "Magnolia", district: 3, area: "North Sector Residential" },
    { name: "Mallard Way", district: 3, area: "Rolling Meadows & Northern Subdivisions" },
    { name: "Maple St", district: 1, area: "Historic Downtown Core / WCHS Campus" },
    { name: "Mar Vista Dr", district: 2, area: "West Sector Residential" },
    { name: "Market St", district: 1, area: "Downtown Square Core" },
    { name: "Mc Ginley St", district: 2, area: "West Sector Residential" },
    { name: "McClugage Rd", district: 2, area: "West Sector Residential" },
    { name: "McCluggage Rd", district: 2, area: "West Sector Residential" },
    { name: "McGinley St", district: 2, area: "West Sector Residential" },
    { name: "Meadow Ave", district: 2, area: "Meadow Valley Corridor" },
    { name: "Melvin St", district: 1, area: "East Sector Residential" },
    { name: "Metamora Rd", district: 1, area: "East Sector Residential" },
    { name: "Michael Ct", district: 1, area: "East Sector Residential" },
    { name: "Miller St", district: 1, area: "East Sector Residential" },
    { name: "Mitchell St", district: 3, area: "North Sector Residential" },
    { name: "Monroe", district: 1, area: "Historic Downtown Core / WCHS Campus" },
    { name: "Monroe St", district: 1, area: "Historic Downtown Core / WCHS Campus" },
    { name: "Morris St", district: 1, area: "East Sector Residential" },
    { name: "Mount Vernon Dr", district: 3, area: "North Sector Residential" },
    { name: "Muller Rd", district: 2, area: "West Sector Residential" },
    { name: "N Cedar St", district: 1, area: "Historic Downtown Core / WCHS Campus" },
    { name: "N Church St", district: 1, area: "East Sector Residential" },
    { name: "N Cummings Ln", district: 3, area: "West Sector Artery / School Corridor" },
    { name: "N Elm St", district: 1, area: "Historic Downtown Core / WCHS Campus" },
    { name: "N High", district: 1, area: "Historic Downtown Core / WCHS Campus" },
    { name: "N High St", district: 1, area: "Historic Downtown Core / WCHS Campus" },
    { name: "N Lawndale Ave", district: 1, area: "East Sector Residential" },
    { name: "N Main St", district: 1, area: "Historic Downtown Core / WCHS Campus" },
    { name: "N Market St", district: 1, area: "Historic Downtown Core / WCHS Campus" },
    { name: "N Meadowview Ln", district: 2, area: "West Sector Artery / School Corridor" },
    { name: "N Pine St", district: 1, area: "Historic Downtown Core / WCHS Campus" },
    { name: "N Spruce St", district: 1, area: "Historic Downtown Core / WCHS Campus" },
    { name: "N St", district: 1, area: "East Sector Residential" },
    { name: "N Wilmor Rd", district: 3, area: "Five Points / North Wilmor Corridor" },
    { name: "N Wood", district: 1, area: "Historic Downtown Core / WCHS Campus" },
    { name: "N Wood St", district: 1, area: "Historic Downtown Core / WCHS Campus" },
    { name: "Newcastle Rd", district: 3, area: "Central Primary School Corridor" },
    { name: "Nofsinger Rd", district: 3, area: "Cruger Bypass / North Corridor" },
    { name: "North Cedar St", district: 1, area: "Historic Downtown Core / WCHS Campus" },
    { name: "North Church St", district: 1, area: "East Sector Residential" },
    { name: "North Cummings Ln", district: 3, area: "West Sector Artery / School Corridor" },
    { name: "North Elm St", district: 1, area: "Historic Downtown Core / WCHS Campus" },
    { name: "North High", district: 1, area: "Historic Downtown Core / WCHS Campus" },
    { name: "North High St", district: 1, area: "Historic Downtown Core / WCHS Campus" },
    { name: "North Lawndale Ave", district: 1, area: "East Sector Residential" },
    { name: "North Main St", district: 1, area: "Washington Middle School Corridor" },
    { name: "North Market St", district: 1, area: "Historic Downtown Core / WCHS Campus" },
    { name: "North Meadowview Ln", district: 2, area: "West Sector Artery / School Corridor" },
    { name: "North Pine St", district: 1, area: "Historic Downtown Core / WCHS Campus" },
    { name: "North Spruce St", district: 1, area: "Historic Downtown Core / WCHS Campus" },
    { name: "North St", district: 1, area: "East Sector Residential" },
    { name: "North Wilmor Rd", district: 3, area: "Five Points / North Wilmor Corridor" },
    { name: "North Wood", district: 1, area: "Historic Downtown Core / WCHS Campus" },
    { name: "North Wood St", district: 1, area: "Historic Downtown Core / WCHS Campus" },
    { name: "Northgate Rd", district: 2, area: "West Residential Subdivisions" },
    { name: "Northridge Ct", district: 2, area: "West Sector Residential" },
    { name: "Northridge Ln", district: 2, area: "West Sector Residential" },
    { name: "Oak Creek Dr", district: 3, area: "Oak Creek Subdivisions" },
    { name: "Oak Rdg", district: 3, area: "North Sector Residential" },
    { name: "Oakland Ave", district: 1, area: "East Sector Residential" },
    { name: "Oakwood Cir", district: 1, area: "Historic Downtown Core / WCHS Campus" },
    { name: "Oakwood Dr", district: 1, area: "Historic Downtown Core / WCHS Campus" },
    { name: "Oakwood Ln", district: 1, area: "Historic Downtown Core / WCHS Campus" },
    { name: "Oxford Ave", district: 3, area: "North Residential Subdivisions" },
    { name: "Oxford Ct", district: 2, area: "West Sector Residential" },
    { name: "Par-Hue Ln", district: 1, area: "East Sector Residential" },
    { name: "Parkview Dr", district: 2, area: "West Sector Residential" },
    { name: "Parr Hue Ln", district: 1, area: "East Sector Residential" },
    { name: "Patricia St", district: 3, area: "North Sector Residential" },
    { name: "Peach St", district: 2, area: "West Sector Residential" },
    { name: "Peddlers Way", district: 1, area: "East Sector Residential" },
    { name: "Penney Ln", district: 1, area: "East Sector Residential" },
    { name: "Penny Ln", district: 1, area: "East Sector Residential" },
    { name: "Peoria St", district: 2, area: "ALDI / West Commercial Corridor (Bus 24)" },
    { name: "Peppertree Ct", district: 2, area: "West Sector Residential" },
    { name: "Pin Oak Ct", district: 3, area: "North Sector Residential" },
    { name: "Pine Dr", district: 2, area: "West Residential" },
    { name: "Pine Ridge Dr", district: 2, area: "Historic Downtown Core / WCHS Campus" },
    { name: "Pine St", district: 1, area: "East Core Residential" },
    { name: "Pine Tree Dr", district: 1, area: "Historic Downtown Core / WCHS Campus" },
    { name: "Pintail Ln", district: 3, area: "Rolling Meadows & Northern Subdivisions" },
    { name: "Plymouth Ct", district: 2, area: "West Sector Residential" },
    { name: "Polk", district: 1, area: "Historic Downtown Core / WCHS Campus" },
    { name: "Polk St", district: 1, area: "Historic Downtown Core / WCHS Campus" },
    { name: "Poplar Ln", district: 2, area: "West Sector Residential" },
    { name: "Poplar St", district: 2, area: "West Sector Residential" },
    { name: "Primrose Ln", district: 2, area: "West Sector Residential" },
    { name: "Prince George Ct", district: 1, area: "Devonshire Estates / East Subdivisions" },
    { name: "Ragan Ct", district: 2, area: "West Sector Residential" },
    { name: "Ransom Rd", district: 2, area: "West Sector Commercial" },
    { name: "Redbud Dr", district: 1, area: "East Sector Residential" },
    { name: "Remington Way", district: 3, area: "North Sector Residential" },
    { name: "Retriever Ln", district: 3, area: "North Sector Residential" },
    { name: "Ridge St", district: 1, area: "East Sector Residential" },
    { name: "Ridgecrest Dr", district: 1, area: "East Sector Residential" },
    { name: "Rockaway", district: 1, area: "East Sector Residential" },
    { name: "Rockaway Rd", district: 1, area: "East Sector Residential" },
    { name: "Rolling Meadows Dr", district: 3, area: "Rolling Meadows Subdivisions" },
    { name: "Roxbury Ln", district: 2, area: "West Sector Residential" },
    { name: "Royal Ct", district: 1, area: "East Sector Residential" },
    { name: "Rustic Oak Dr", district: 3, area: "North Sector Residential" },
    { name: "Ryan Ln", district: 3, area: "North Sector Residential" },
    { name: "S Cedar St", district: 1, area: "Historic Downtown Core / WCHS Campus" },
    { name: "S Church St", district: 1, area: "East Sector Residential" },
    { name: "S Cummings Ln", district: 2, area: "West Sector Artery / School Corridor" },
    { name: "S Elm St", district: 1, area: "Historic Downtown Core / WCHS Campus" },
    { name: "S High St", district: 1, area: "Historic Downtown Core / WCHS Campus" },
    { name: "S Lawndale St", district: 1, area: "East Sector Residential" },
    { name: "S Main", district: 1, area: "Historic Downtown Core / WCHS Campus" },
    { name: "S Main St", district: 1, area: "Historic Downtown Core / WCHS Campus" },
    { name: "S Market", district: 1, area: "Historic Downtown Core / WCHS Campus" },
    { name: "S Market St", district: 1, area: "Historic Downtown Core / WCHS Campus" },
    { name: "S Meadowview Ln", district: 2, area: "West Sector Artery / School Corridor" },
    { name: "S Pine St", district: 1, area: "Historic Downtown Core / WCHS Campus" },
    { name: "S School St", district: 2, area: "West Sector Artery / School Corridor" },
    { name: "S Spruce St", district: 1, area: "Historic Downtown Core / WCHS Campus" },
    { name: "S St", district: 1, area: "East Sector Residential" },
    { name: "S Wood St", district: 1, area: "Historic Downtown Core / WCHS Campus" },
    { name: "Saddleridge Ct", district: 2, area: "West Sector Residential" },
    { name: "Santa Fe Rd", district: 3, area: "North Sector Residential" },
    { name: "Savile Ln", district: 3, area: "North Sector Residential" },
    { name: "School St", district: 2, area: "West Residential / School Corridor" },
    { name: "Seaton Ln", district: 2, area: "West Sector Residential" },
    { name: "Shell Bark Ct", district: 1, area: "East Sector Residential" },
    { name: "Shellbark Ct", district: 1, area: "East Sector Residential" },
    { name: "Simon St", district: 3, area: "North Sector Residential" },
    { name: "Somerset Ct", district: 1, area: "Devonshire Estates / East Subdivisions" },
    { name: "Sonny Dr", district: 2, area: "West Sector Residential" },
    { name: "South Cedar St", district: 1, area: "Historic Downtown Core / WCHS Campus" },
    { name: "South Church St", district: 1, area: "East Sector Residential" },
    { name: "South Cummings Ln", district: 2, area: "West Residential / Commercial Artery" },
    { name: "South Elm St", district: 1, area: "Historic Downtown Core / WCHS Campus" },
    { name: "South High St", district: 1, area: "Historic Downtown Core / WCHS Campus" },
    { name: "South Lawndale St", district: 1, area: "East Sector Residential" },
    { name: "South Main", district: 1, area: "Historic Downtown Core / WCHS Campus" },
    { name: "South Main St", district: 1, area: "Downtown Core Corridor" },
    { name: "South Market", district: 1, area: "Historic Downtown Core / WCHS Campus" },
    { name: "South Market St", district: 1, area: "Historic Downtown Core / WCHS Campus" },
    { name: "South Meadowview Ln", district: 2, area: "West Sector Artery / School Corridor" },
    { name: "South Pine St", district: 1, area: "Historic Downtown Core / WCHS Campus" },
    { name: "South School St", district: 2, area: "West Sector Artery / School Corridor" },
    { name: "South Spruce St", district: 1, area: "Fire Station 2 Corridor" },
    { name: "South St", district: 1, area: "East Sector Residential" },
    { name: "South Wood St", district: 1, area: "Historic Downtown Core / WCHS Campus" },
    { name: "Southgate Rd", district: 2, area: "West Residential Subdivisions" },
    { name: "Spring Creek Rd", district: 2, area: "Historic Downtown Core / WCHS Campus" },
    { name: "Spring St", district: 1, area: "Historic Downtown Core / WCHS Campus" },
    { name: "St Clare Ct", district: 3, area: "North Sector Residential" },
    { name: "State Route 8 (Peoria St / Washington Rd)", district: 2, area: "Historic Downtown Core / WCHS Campus" },
    { name: "State St", district: 1, area: "Historic Downtown Core / WCHS Campus" },
    { name: "Steeplechase", district: 2, area: "West Sector Residential" },
    { name: "Stephanie Ct", district: 3, area: "North Sector Residential" },
    { name: "Sterling St", district: 2, area: "West Sector Residential" },
    { name: "Stonegate", district: 2, area: "West Sector Residential" },
    { name: "Stonehenge Ct", district: 1, area: "East Sector Residential" },
    { name: "Stoneridge", district: 2, area: "West Sector Residential" },
    { name: "Stoneway Dr", district: 3, area: "North Sector Residential" },
    { name: "Stratford Ct", district: 1, area: "Devonshire Estates / East Subdivisions" },
    { name: "Stratford Dr", district: 3, area: "North Residential Subdivisions" },
    { name: "Streamwood Ct", district: 2, area: "Historic Downtown Core / WCHS Campus" },
    { name: "Summit Dr", district: 2, area: "West Ridge Residential" },
    { name: "Sunburst Ln", district: 2, area: "West Sector Residential" },
    { name: "Sunnyland Plaza", district: 2, area: "West Sector Residential" },
    { name: "Sunset Dr", district: 2, area: "West Sector Residential" },
    { name: "Sycamore", district: 3, area: "North Sector Residential" },
    { name: "Taft", district: 1, area: "Historic Downtown Core / WCHS Campus" },
    { name: "Taft St", district: 1, area: "Historic Downtown Core / WCHS Campus" },
    { name: "Terrace", district: 1, area: "East Sector Residential" },
    { name: "Terrace Ct", district: 1, area: "East Sector Residential" },
    { name: "Tiezzi Ln", district: 1, area: "East Sector Residential" },
    { name: "Timber Rail Dr", district: 2, area: "West Sector Residential" },
    { name: "Tottenham Ct", district: 1, area: "East Sector Residential" },
    { name: "Trl End", district: 2, area: "West Sector Residential" },
    { name: "Tyler", district: 1, area: "Historic Downtown Core / WCHS Campus" },
    { name: "Tyler St", district: 1, area: "Historic Downtown Core / WCHS Campus" },
    { name: "US Route 24 Business", district: 1, area: "Freedom Pkwy / West Commercial Corridor" },
    { name: "US Route 24 Bypass", district: 1, area: "Cruger Bypass / North Corridor" },
    { name: "Valley Forge Dr", district: 2, area: "West Sector Residential" },
    { name: "Velma St", district: 2, area: "Historic Downtown Core / WCHS Campus" },
    { name: "Victoria Dr", district: 1, area: "East Sector Residential" },
    { name: "Vine St", district: 1, area: "East Sector Residential" },
    { name: "Vohland St", district: 2, area: "West Sector Residential" },
    { name: "W Adams", district: 1, area: "Historic Downtown Core / WCHS Campus" },
    { name: "W Adams St", district: 1, area: "Historic Downtown Core / WCHS Campus" },
    { name: "W Cruger Rd", district: 3, area: "Cruger Bypass / North Corridor" },
    { name: "W Guth Rd", district: 1, area: "East Sector Residential" },
    { name: "W Holland St", district: 1, area: "Historic Downtown Core / WCHS Campus" },
    { name: "W Jefferson", district: 1, area: "Historic Downtown Core / WCHS Campus" },
    { name: "W Jefferson St", district: 1, area: "Historic Downtown Core / WCHS Campus" },
    { name: "W Peoria St", district: 2, area: "West Commercial Corridor" },
    { name: "W St", district: 1, area: "East Sector Residential" },
    { name: "W Yorktown Ct", district: 2, area: "West Sector Residential" },
    { name: "Wagner St", district: 2, area: "West Sector Residential" },
    { name: "Walnut St", district: 1, area: "City Hall / Downtown Commercial" },
    { name: "Washington Rd", district: 2, area: "Business Route 24 Commercial Corridor" },
    { name: "Washington Square", district: 1, area: "Historic Downtown Square" },
    { name: "Weaver St", district: 2, area: "West Sector Residential" },
    { name: "Wellington Dr", district: 1, area: "Devonshire East Subdivisions" },
    { name: "West Adams", district: 1, area: "Historic Downtown Core / WCHS Campus" },
    { name: "West Adams St", district: 1, area: "Historic Downtown Core / WCHS Campus" },
    { name: "West Cruger Rd", district: 3, area: "North Cruger Bypass Corridor" },
    { name: "West Guth Rd", district: 1, area: "East Sector Residential" },
    { name: "West Holland St", district: 1, area: "Historic Downtown Core / WCHS Campus" },
    { name: "West Jefferson", district: 1, area: "Historic Downtown Core / WCHS Campus" },
    { name: "West Jefferson St", district: 1, area: "WPD Headquarters / Core Corridor" },
    { name: "West Peoria St", district: 2, area: "West Commercial Corridor" },
    { name: "West St", district: 1, area: "East Sector Residential" },
    { name: "West Yorktown Ct", district: 2, area: "West Sector Residential" },
    { name: "Westgate Rd", district: 2, area: "West Residential Subdivisions" },
    { name: "Westminster Dr", district: 1, area: "Devonshire Estates / East Subdivisions" },
    { name: "White Oak Ct", district: 3, area: "North Sector Residential" },
    { name: "White Tail Dr", district: 3, area: "Rolling Meadows & Northern Subdivisions" },
    { name: "Wigeon Pl", district: 3, area: "North Sector Residential" },
    { name: "Wildwood Ct", district: 2, area: "Historic Downtown Core / WCHS Campus" },
    { name: "Willa Ln", district: 2, area: "West Sector Residential" },
    { name: "William St", district: 2, area: "West Sector Residential" },
    { name: "Willow Dr", district: 3, area: "North Sector Residential" },
    { name: "Wilmor Rd", district: 3, area: "Five Points / North Wilmor Corridor" },
    { name: "Wilshire Ct", district: 1, area: "East Sector Residential" },
    { name: "Wilshire Dr", district: 1, area: "East Sector Residential" },
    { name: "Winchester Dr", district: 1, area: "Devonshire Estates / East Subdivisions" },
    { name: "Windsor Way", district: 1, area: "Devonshire Estates / East Subdivisions" },
    { name: "Winterberry Ct", district: 2, area: "West Sector Residential" },
    { name: "Wisteria Way", district: 2, area: "West Sector Residential" },
    { name: "Wood St", district: 1, area: "East Sector Corridor" },
    { name: "Woodcrest Dr", district: 1, area: "Historic Downtown Core / WCHS Campus" },
    { name: "Woodland Trl", district: 2, area: "Historic Downtown Core / WCHS Campus" },
    { name: "Woodridge Dr", district: 2, area: "West Subdivisions" },
    { name: "Woodview Ct", district: 2, area: "Historic Downtown Core / WCHS Campus" },
    { name: "Yorkshire Ct", district: 1, area: "Devonshire Estates / East Subdivisions" },
    { name: "Yorkshire Dr", district: 1, area: "Devonshire Estates / East Subdivisions" },
    { name: "Zinser Pl", district: 1, area: "Dement-Zinser Historic Core" }
  ],

  /* Services Catalog - Strict Direct Link vs 5 Gap Smart Form Drawers */
  services1Click: [
    {
      id: "vacation-check",
      title: "Vacation House Watch",
      badge: "Official City Portal ↗",
      desc: "Enroll directly in periodic patrol exterior security checks while traveling away from Washington.",
      actionText: "Enroll on City Portal ↗",
      isExternal: true,
      url: "https://www.ci.washington.il.us/egov/apps/action/center.egov?view=form;page=1;id=15"
    },
    {
      id: "parking-permits",
      title: "Overnight Street Parking Permits",
      badge: "Direct WPD Workflow →",
      desc: "Request temporary exemption from 2:00 AM – 6:00 AM street parking restriction (§ 72.02).",
      actionText: "Request Parking Permit →",
      drawerId: "drawer-parking-permits"
    },
    {
      id: "payments-parking",
      title: "Pay Parking Ticket Online",
      badge: "Official City Portal ↗",
      desc: "Direct online settlement for City of Washington parking tickets and violation citations.",
      actionText: "Pay Ticket Online ↗",
      isExternal: true,
      url: "https://www.ci.washington.il.us/egov/apps/payment/center.egov?view=form;page=1;id=21"
    },
    {
      id: "police-records",
      title: "Police Records & FOIA",
      badge: "Official City Portal ↗",
      desc: "Submit statutory Illinois FOIA filings or request official incident reports directly to City Hall.",
      actionText: "Submit City FOIA ↗",
      isExternal: true,
      url: "https://www.ci.washington.il.us/egov/apps/action/center.egov?view=form;page=1;id=179"
    },
    {
      id: "bicycle-registration",
      title: "Bicycle Identification Registry",
      badge: "Direct WPD Workflow →",
      desc: "Register bicycle serial number and frame details for rapid recovery if lost or stolen.",
      actionText: "Register Bicycle →",
      drawerId: "drawer-bicycle-registration"
    },
    {
      id: "crash-reports",
      title: "Accident & Crash Reports",
      badge: "State Partner Portal ↗",
      desc: "Obtain official State of Illinois traffic crash reports online through BuyCrash.",
      actionText: "Search Crash Portal ↗",
      isExternal: true,
      url: "https://buycrash.lexisnexisrisk.com/"
    },
    {
      id: "anonymous-tip",
      title: "Submit an Anonymous Tip",
      badge: "Direct WPD Workflow →",
      desc: "Share 100% confidential intelligence regarding narcotics or investigations without revealing your identity.",
      actionText: "Send Confidential Tip →",
      drawerId: "drawer-anonymous-tip"
    },
    {
      id: "child-safety-seat",
      title: "Child Safety Seat Inspection",
      badge: "Direct WPD Workflow →",
      desc: "Book a free installation inspection with state-certified Child Passenger Safety officers.",
      actionText: "Book Inspection →",
      drawerId: "drawer-child-seat"
    },
    {
      id: "commend-officer",
      title: "Commend an Officer / Feedback",
      badge: "Direct WPD Workflow →",
      desc: "Recognize an officer for exceptional field service or share constructive feedback.",
      actionText: "Submit Commendation →",
      drawerId: "drawer-commendation"
    },
    {
      id: "drug-disposal",
      title: "Safe Medication Disposal",
      badge: "HQ Walk-In Kiosk",
      desc: "Dispose of expired or unused medications safely in our permanent 24/7 lobby drop box.",
      actionText: "Drop Box Guidelines",
      isInternalLink: true,
      url: "services.html#drug-disposal"
    },
    {
      id: "codered-alerts",
      title: "CodeRED Emergency Alerts",
      badge: "County System ↗",
      desc: "Receive urgent emergency notifications, weather warnings, and critical safety updates.",
      actionText: "Enroll in CodeRED ↗",
      isExternal: true,
      url: "https://public.coderedweb.com/CNE/en-US/BF8738F9B6E9"
    }
  ],

  specializedUnits: [
    {
      name: "CIERT Tactical & Crisis Negotiation",
      code: "REGIONAL SWAT",
      desc: "Washington participates in the Central Illinois Emergency Response Team with tactical officers and certified crisis negotiators dedicated to high-risk incident resolution.",
      officersAssigned: "6 Officers & Negotiators"
    },
    {
      name: "School Resource Program (SRO)",
      code: "YOUTH SAFETY",
      desc: "Full-time dedicated officers stationed directly at Washington Community High School (District 308) and Central School District 51 to provide daily safety, mentoring, and student support.",
      officersAssigned: "Dedicated SROs"
    },
    {
      name: "Cybercrime & Crimes Against Children",
      code: "TASK FORCE",
      desc: "Investigators cross-deputized with the Homeland Security Investigations Cybercrime Task Force and the Illinois Attorney General's Crimes Against Children Task Force.",
      officersAssigned: "Specialized Detectives"
    },
    {
      name: "Part-Time Police Unit",
      code: "COMMUNITY SUPPORT",
      desc: "10 state-certified sworn officers who augment full-time personnel, providing event security, Washington Square festival patrols, park safety, and emergency surge staffing.",
      officersAssigned: "10 Sworn Officers"
    },
    {
      name: "Canine Unit (K-9)",
      code: "SPECIALIZED PATROL",
      desc: "Dual-purpose police service dog team trained in narcotics detection, tracking, area searches, and handler protection.",
      officersAssigned: "K-9 Team"
    }
  ],

  recruitment: {
    startingSalary: "$68,500 – $84,200 (CBA Scale)",
    lateralBonus: "Accelerated Pay Step for Experienced Officers",
    benefits: [
      "100% City-paid medical, dental, and life insurance options",
      "Tier 2 Police Pension Fund enrollment",
      "Department-issued individual patrol rifles and modern optics",
      "Quarterly firearms and tactical qualification program",
      "Department gym facility & fitness incentive stipends",
      "Twice-annual seniority shift bidding (May & November)"
    ],
    applicationPdf: "https://www.ci.washington.il.us/egov/apps/document/center.egov?view=item&id=2040",
    partTimePdf: "https://www.ci.washington.il.us/egov/apps/document/center.egov?view=item&id=2074",
    cbaPdf: "https://www.ci.washington.il.us/egov/apps/document/center.egov?view=item&id=2569"
  }
};

/* ==========================================================================
   WPD CIVIC COMMAND SEARCH INDEX (⌘K / Ctrl+K Palette)
   Tags: city-portal (External ↗), wpd-drawer (Instant ⚡), partner (↗), nav, phone
   ========================================================================== */
const WPD_COMMAND_SEARCH_INDEX = [
  /* Official City of Washington Forms (Direct Link Out) */
  {
    title: "Vacation House Watch Enrollment",
    category: "Official City Portals",
    type: "city-portal",
    action: "https://www.ci.washington.il.us/egov/apps/action/center.egov?view=form;page=1;id=15",
    badge: "Official City Form ↗",
    keywords: "vacation house watch property check travel away out of town patrol exterior security home residential premises check",
    desc: "Direct deep-link to City of Washington eGov Action Center Form #15"
  },
  {
    title: "Pay Parking Ticket Online",
    category: "Official City Portals",
    type: "city-portal",
    action: "https://www.ci.washington.il.us/egov/apps/payment/center.egov?view=form;page=1;id=21",
    badge: "Official City Payment ↗",
    keywords: "pay parking ticket citation violation fine settle online credit card egov tyler technologies municipal",
    desc: "City of Washington eGov Payment Center Form #21"
  },
  {
    title: "Pay Ordinance Violation Notice",
    category: "Official City Portals",
    type: "city-portal",
    action: "https://www.ci.washington.il.us/egov/apps/payment/center.egov?view=form;page=1;id=22",
    badge: "Official City Payment ↗",
    keywords: "notice of violation ordinance code compliance fine payment administrative citation",
    desc: "City of Washington eGov Payment Center Form #22"
  },
  {
    title: "Vehicle Impound Tow Bond Release",
    category: "Official City Portals",
    type: "city-portal",
    action: "https://www.ci.washington.il.us/egov/apps/payment/center.egov?view=form;page=1;id=23",
    badge: "Official City Payment ↗",
    keywords: "impound tow bond vehicle release towing fee administrative fee car retrieval",
    desc: "City of Washington eGov Payment Center Form #23"
  },
  {
    title: "Police Records & FOIA Submission",
    category: "Official City Portals",
    type: "city-portal",
    action: "https://www.ci.washington.il.us/egov/apps/action/center.egov?view=form;page=1;id=179",
    badge: "Official City Form ↗",
    keywords: "police records foia statutory freedom of information act 5 ilcs 140 incident report accident case public records request",
    desc: "City of Washington eGov Action Center Form #179"
  },
  {
    title: "Full-Time Police Officer Application (PDF)",
    category: "Official City Portals",
    type: "city-portal",
    action: "https://www.ci.washington.il.us/egov/apps/document/center.egov?view=item&id=2040",
    badge: "Official City Document ↗",
    keywords: "apply full time officer sworn police recruit careers job hiring application packet document",
    desc: "Official City of Washington Police Application Packet (Item #2040)"
  },
  {
    title: "Part-Time Police Officer Application (PDF)",
    category: "Official City Portals",
    type: "city-portal",
    action: "https://www.ci.washington.il.us/egov/apps/document/center.egov?view=item&id=2074",
    badge: "Official City Document ↗",
    keywords: "part time police officer application careers hiring sworn unit pdf document",
    desc: "Official City Part-Time Application (Item #2074)"
  },
  {
    title: "Citizen Police Academy Application (PDF)",
    category: "Official City Portals",
    type: "city-portal",
    action: "https://www.ci.washington.il.us/egov/apps/document/center.egov?view=item&id=2764",
    badge: "Official City Document ↗",
    keywords: "citizen police academy cpa community class education enrollment application pdf document",
    desc: "Official CPA Application Form (Item #2764)"
  },

  /* State & County Partner Portals */
  {
    title: "Traffic Crash & Accident Reports (BuyCrash)",
    category: "Partner Portals",
    type: "partner-portal",
    action: "https://buycrash.lexisnexisrisk.com/",
    badge: "State Partner Portal ↗",
    keywords: "accident crash reports buycrash collision traffic crash records lexisnexis state illinois insurance claim",
    desc: "Official State of Illinois collision records repository via BuyCrash"
  },
  {
    title: "CodeRED Community Emergency Alerts",
    category: "Partner Portals",
    type: "partner-portal",
    action: "https://public.coderedweb.com/CNE/en-US/BF8738F9B6E9",
    badge: "County Alert System ↗",
    keywords: "codered emergency alerts weather tornado severe storm boil order road closure telephone notification",
    desc: "Tazewell County high-speed emergency citizen notification network"
  },

  /* Strictly 5 Gap In-App Smart Form Drawers */
  {
    title: "Overnight & Street Parking Permit (§ 72.02)",
    category: "WPD Smart Forms",
    type: "wpd-drawer",
    action: "drawer-parking-permits",
    badge: "Direct WPD Workflow →",
    keywords: "parking permit overnight street 2am 6am exemption waiver camper rv trailer moving van guest breakdown section 72.02",
    desc: "Instant electronic registration for 2:00 AM – 6:00 AM street parking exemption"
  },
  {
    title: "Bicycle Identification & Registration",
    category: "WPD Smart Forms",
    type: "wpd-drawer",
    action: "drawer-bicycle-registration",
    badge: "Direct WPD Workflow →",
    keywords: "bicycle bike registration serial number crime prevention theft recovery frame color make model",
    desc: "Free crime prevention registry for personal bicycle recovery"
  },
  {
    title: "Submit Confidential Anonymous Crime Tip",
    category: "WPD Smart Forms",
    type: "wpd-drawer",
    action: "drawer-anonymous-tip",
    badge: "Direct WPD Workflow →",
    keywords: "anonymous crime tip confidential intelligence report narcotics drugs tip411 suspicious activity investigation",
    desc: "100% confidential encrypted intelligence transmission to WPD detectives"
  },
  {
    title: "Child Safety Seat Inspection Booking",
    category: "WPD Smart Forms",
    type: "wpd-drawer",
    action: "drawer-child-seat",
    badge: "Direct WPD Workflow →",
    keywords: "child safety seat car seat inspection certified technician installation appointment infant booster cps",
    desc: "Schedule a free installation inspection with state-certified CPS technicians"
  },
  {
    title: "Commend an Officer / Citizen Feedback",
    category: "WPD Smart Forms",
    type: "wpd-drawer",
    action: "drawer-commendation",
    badge: "Direct WPD Workflow →",
    keywords: "commend officer recognition compliment feedback praise exceptional service review command staff",
    desc: "Recognize an officer for exemplary service or submit formal citizen feedback"
  },

  /* Civic Walk-In & GIS Resolver */
  {
    title: "Safe Medication & Prescription Drop Box",
    category: "Civic Services",
    type: "nav-link",
    action: "services.html#drug-disposal",
    badge: "HQ Walk-In Kiosk",
    keywords: "medication disposal prescription drug pills drop box headquarters lobby safe disposal narcotics 24/7",
    desc: "Permanent 24/7 lobby collection kiosk at 115 W. Jefferson St"
  },
  {
    title: "Find Your Patrol Beat & Assigned Cruiser",
    category: "Civic Services",
    type: "nav-link",
    action: "districts.html#address-resolver",
    badge: "GIS Beat Resolver",
    keywords: "district sector patrol beat map address street lookup find my officer car 101 car 102 car 103",
    desc: "Interactive street-to-patrol sector GIS resolver and assigned unit display"
  },
  {
    title: "Call 24/7 Police Dispatch Line",
    category: "Direct Dispatch",
    type: "phone",
    action: "tel:3094442313",
    badge: "(309) 444-2313",
    keywords: "dispatch non emergency telephone call phone officer speak report 444-2313 communications",
    desc: "Connect directly to on-duty Tazewell County dispatchers for Washington"
  },
  {
    title: "Emergency Life Safety Dispatch (911)",
    category: "Direct Dispatch",
    type: "phone",
    action: "tel:911",
    badge: "DIAL 911",
    keywords: "911 emergency immediate danger life threat active crime weapon violence fire medical ambulance",
    desc: "Immediate priority dispatch for life-safety emergencies and crimes in progress"
  },

  /* Department Portals Navigation */
  {
    title: "Executive Home & Command Overview",
    category: "Department Navigation",
    type: "nav-link",
    action: "index.html",
    badge: "Page",
    keywords: "home executive command headquarters chief jeff stevens mission values overview",
    desc: "Department landing page, emergency triage, and executive leadership summary"
  },
  {
    title: "Resident Services Directory",
    category: "Department Navigation",
    type: "nav-link",
    action: "services.html",
    badge: "Page",
    keywords: "services resident directory permits payments records forms faq knowledge base",
    desc: "Full catalog of 14 municipal resident services and FAQ knowledge base"
  },
  {
    title: "Patrol Districts & Tactical GIS Map",
    category: "Department Navigation",
    type: "nav-link",
    action: "districts.html",
    badge: "Page",
    keywords: "districts map sectors gis geography boundaries sector 1 sector 2 sector 3",
    desc: "Interactive sector map, street boundaries, and assigned sector cruisers"
  },
  {
    title: "Patrol Operations & Shift Schedules",
    category: "Department Navigation",
    type: "nav-link",
    action: "operations.html",
    badge: "Page",
    keywords: "operations patrol shifts day afternoon night watch fleet cruisers equipment 24/7",
    desc: "24/7 watch schedule, operational capabilities, and patrol fleet telemetry"
  },
  {
    title: "Specialized Divisions (CIERT, K-9, SRO)",
    category: "Department Navigation",
    type: "nav-link",
    action: "teams.html",
    badge: "Page",
    keywords: "teams divisions swat ciert k9 canine sro school resource cybercrime detectives investigators",
    desc: "Tactical response, canine unit, youth school safety, and investigative task forces"
  },
  {
    title: "Careers, Recruitment & Benefits",
    category: "Department Navigation",
    type: "nav-link",
    action: "recruitment.html",
    badge: "Page",
    keywords: "careers recruitment jobs hiring police officer salary benefits pension lateral sworn test",
    desc: "Officer compensation, lateral entry incentives, CBA scale, and application steps"
  },
  {
    title: "Community Outreach & Programs",
    category: "Department Navigation",
    type: "nav-link",
    action: "community.html",
    badge: "Page",
    keywords: "community outreach citizens police academy cpa watch programs youth safety stuffed animals",
    desc: "Citizen Academy, youth programs, neighborhood partnerships, and comfort initiatives"
  },
  {
    title: "Leadership & Governance Matrix",
    category: "Department Navigation",
    type: "nav-link",
    action: "leadership.html",
    badge: "Page",
    keywords: "leadership governance chief jeff stevens deputy chiefs steve smith brian simpson sergeants command",
    desc: "Command hierarchy, deputy chiefs, field sergeants, and board oversight"
  }
];

if (typeof module !== 'undefined' && module.exports) {
  module.exports = { WPD_DATA, WPD_COMMAND_SEARCH_INDEX };
}
